import { Navbar } from '@/components/layout/Navbar'
import Link from 'next/link'

// Static example skill files for SEO
const EXAMPLES: Record<string, { name: string; domain: string; skillFile: string }> = {
  apple: {
    name: 'Apple',
    domain: 'apple.com',
    skillFile: `---
name: Apple Brand Identity System
description: Apply Apple's complete brand identity to all generated content. Use whenever creating copy, social posts, product descriptions, or presentations for Apple or Apple-adjacent brands.
---

## Brand overview
Apple communicates through restraint. Every word is chosen because it cannot be removed. The brand doesn't explain — it reveals. Copy is confident to the point of audacity, yet never arrogant.

## Voice & tone rules

### Rule 1 — Lead with the feeling, not the feature
DO: "The camera that sees what your eye misses."
DON'T: "12MP camera with advanced computational photography"

### Rule 2 — Sentences end. Not lists.
DO: "Fast. Beautiful. Yours."
DON'T: "• Fast performance • Beautiful design • Personalized experience"

### Rule 3 — Lowercase the technology, capitalize the human
DO: "Shot on iPhone. By you."
DON'T: "Captured Using iPhone 16 Pro's Advanced LiDAR System"

### Rule 4 — One idea per sentence. No conjunctions.
DO: "All-day battery. All-night confidence."
DON'T: "It has all-day battery life and you can use it all night without worrying."

### Rule 5 — The product is the proof. Don't argue.
DO: "This is iPhone."
DON'T: "iPhone is the best smartphone on the market because..."

## Visual identity

### Colors
- Primary: #1d1d1f — near-black, used for headlines and primary text
- Secondary: #f5f5f7 — off-white, used for backgrounds and breathing room
- Accent: #0066cc — Apple blue, used sparingly for links and CTAs only
- White: #ffffff — primary background
- Gray: #86868b — body text, secondary information

### Typography
- Headlines: SF Pro Display — tight tracking, never bold unless size alone isn't enough
- Body: SF Pro Text — 17px minimum, 1.47 line height
- Rule: Never use more than two weights on a single page

### Logo
- Usage: Always monochrome — white on dark, black or dark gray on light
- Clearspace: equal to the height of the Apple mark on all sides
- Never: colored, shadowed, outlined, or placed on busy backgrounds

## Content templates

### Social media — Instagram
Format: [One-sentence claim.] [One word or fragment.] [Period.]
Char limit: Under 100 characters in the caption body
Example: "The display that makes everything else look wrong. Liquid Retina XDR."

### Social media — X/Twitter
Format: [Product name.] [What it does in under 8 words.] [Link]
Example: "iPhone 16. The camera that outthinks the moment."

### Social media — LinkedIn
Format: [Insight or claim.] [Single supporting sentence.] [Soft CTA or reflection.]
Example: "The best tool is the one that disappears. That's what we spent 10 years building into the new MacBook Pro."

### Email subject lines
Formula: [Product]. [Feeling or outcome.]
Examples: "iPhone. Hello, again." / "Mac. Built for what's next."

### Ad creative — headline
Formula: [Adjective or verb]. [Noun.] — maximum 4 words total
Examples: "Think different." / "Shot on iPhone." / "The new MacBook."

### Blog/editorial — opening line
Formula: Start with a contradiction or a fact that reframes the problem.
Example: "Most cameras record light. iPhone understands it."

## Anti-patterns
1. Never use exclamation points. Apple doesn't exclaim.
2. Never say "innovative," "revolutionary," or "game-changing." Show, don't label.
3. Never list more than 3 features. If you need more, cut features, not words.
4. Never write in passive voice. "Apple built" not "was built by Apple."
5. Never anthropomorphize the product excessively. It's a tool, not a friend.

## Image generation guidance
Style: Ultra-minimal, product-centric, cinematic depth of field. Subject floats in near-white or deep space. Lighting is precision-controlled — one key light, no harsh shadows. No humans unless they're using the product. No props, no clutter. The product IS the image.

Palette: Almost-white (#f5f5f7) or deep near-black (#1d1d1f) backgrounds only.

Avoid: Gradients, lens flare, stock-photo aesthetics, busy environments.

## Brand positioning
Apple sells the feeling of creative superiority — the sense that the person using Apple tools is doing their best work. The target is anyone who takes what they do seriously: the photographer, the developer, the student who actually cares. Apple's differentiation is taste: the claim that the details others skip are the details that matter most.

<!-- Generated by BrandSkill.com -->`,
  },
  stripe: {
    name: 'Stripe',
    domain: 'stripe.com',
    skillFile: `---
name: Stripe Brand Identity System
description: Apply Stripe's complete brand identity to all generated content. Use whenever creating developer docs, marketing copy, social posts, or product announcements for Stripe or fintech-adjacent brands.
---

## Brand overview
Stripe writes like a brilliant engineer who also happens to be an exceptional communicator. Copy is technical and precise, but never cold. The brand treats developers as intellectuals, not just users — explaining the "why" behind every decision.

## Voice & tone rules

### Rule 1 — Respect the reader's intelligence
DO: "Stripe uses machine learning to route transactions across acquiring banks based on real-time success rates."
DON'T: "Stripe uses AI to make your payments work better."

### Rule 2 — Lead with the outcome, earn the explanation
DO: "Increase revenue. Stripe Radar blocks fraud without blocking good customers."
DON'T: "Stripe Radar is a fraud detection tool that uses machine learning algorithms."

### Rule 3 — Technical precision over marketing vagueness
DO: "Webhooks deliver events within 200ms of state changes."
DON'T: "Get notified instantly when things happen."

### Rule 4 — Warmth is in the details, not the adjectives
DO: "We built this so you don't have to."
DON'T: "Our amazing team created this incredible feature!"

### Rule 5 — Own the complexity. Don't hide it.
DO: "Reconciliation across 135 currencies is hard. Here's how we solved it."
DON'T: "We handle all the complexity so you don't have to worry about it."

## Visual identity

### Colors
- Primary: #635bff — Stripe purple, the brand's most distinctive element
- Dark: #0a2540 — deep navy, primary for headlines and backgrounds
- Accent: #00d4ff — electric teal, used for highlights and data visualization
- Light: #f6f9fc — page backgrounds, gives the brand its "clean" feel
- Success: #32d583 — used for positive states and growth indicators

### Typography
- Headlines: Sohne — tight, confident, geometric
- Body: Inter — technical clarity at all sizes
- Code: JetBrains Mono — always syntax-highlighted, never plain text

### Logo
- Usage: Full color on white/light; white on dark/purple backgrounds
- The gradient version (purple→teal) is the preferred colored variant
- Never: stretched, rotated, or placed on photographic backgrounds

## Content templates

### Developer documentation — section opener
Formula: [Problem statement.] [How Stripe solves it.] [Code example.]
Example: "Handling webhooks reliably is harder than it sounds. Stripe sends each event with a signature you can verify, so you never have to trust unverified data."

### Social media — X/Twitter
Formula: [Insight or data point.] [What Stripe does about it.] [Link]
Example: "Card-not-present fraud costs merchants $32B/year. Stripe Radar uses 100B+ data points to stop it before it starts."

### Product announcement
Formula: [What exists now that didn't before.] [Why it matters.] [What you can do with it.]

### Email subject lines
Formula: [Specific metric or outcome]: [How]
Examples: "Increase checkout conversion by 11%: new Link data" / "Radar's false positive rate just dropped 30%"

## Anti-patterns
1. Never use "seamless," "powerful," or "robust" — these are Stripe's most-blocked words internally.
2. Never hide the complexity. Developers trust brands that acknowledge hard problems.
3. Never write CTAs as commands without context: "Get started" needs to answer "and then what?"
4. Never use passive voice in technical writing. Own every action.
5. Never use stock imagery of money, coins, or generic "business people." Stripe's imagery is abstract and architectural.

## Image generation guidance
Style: Abstract, mathematical, architectural. Think gradient meshes, 3D geometric forms, flowing data streams. Purple-to-teal gradients on deep navy. The aesthetic is "infrastructure made beautiful" — it should feel like looking at a complex system that's working perfectly.

Avoid: Photos of people handing over credit cards, coins, generic fintech imagery, anything that looks like a bank.

## Brand positioning
Stripe targets ambitious builders — developers and founders who are serious about building great products. The differentiation is intellectual respect: Stripe is the only payment company that treats technical complexity as interesting, not something to hide. Stripe's implicit promise is "we thought about this so deeply that you'll trust us with your most important business logic."

<!-- Generated by BrandSkill.com -->`,
  },
}

// Generate static params for known slugs
export function generateStaticParams() {
  return Object.keys(EXAMPLES).map(slug => ({ slug }))
}

export default function ExamplePage({ params }: { params: { slug: string } }) {
  const example = EXAMPLES[params.slug]

  if (!example) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex flex-col items-center justify-center h-screen gap-4">
          <p className="text-gray-500">Example not found.</p>
          <Link href="/examples" className="text-brand-600 hover:underline">← Back to examples</Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      <main className="pt-24 pb-16 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <Link href="/examples" className="text-gray-400 hover:text-gray-900 text-sm">← Examples</Link>
            <span className="text-gray-300">/</span>
            <span className="text-gray-900 font-medium text-sm">{example.name}</span>
          </div>

          <div className="flex items-start justify-between mb-6">
            <div>
              <h1 className="text-3xl font-black text-gray-900">{example.name} Brand Skill File</h1>
              <p className="text-gray-500 text-sm mt-1 font-mono">{example.domain}</p>
            </div>
            <span className="bg-brand-50 text-brand-700 text-xs px-2 py-1 rounded-full font-semibold">Premium example</span>
          </div>

          <div className="bg-gray-900 rounded-2xl border border-gray-800 overflow-hidden mb-6">
            <div className="flex items-center justify-between px-4 py-3 border-b border-gray-800">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-500" />
                <div className="w-3 h-3 rounded-full bg-yellow-500" />
                <div className="w-3 h-3 rounded-full bg-green-500" />
              </div>
              <span className="text-gray-400 text-xs font-mono">{example.domain.split('.')[0]}-brand-skill.md</span>
              <div />
            </div>
            <div className="p-4 overflow-auto max-h-[70vh] skill-file-preview text-green-400">
              {example.skillFile}
            </div>
          </div>

          <div className="flex gap-3 mb-8">
            <Link
              href="/generate"
              className="flex-1 text-center bg-brand-600 text-white py-4 rounded-xl font-bold hover:bg-brand-700 transition-colors shadow-lg shadow-brand-200"
            >
              Generate for your brand →
            </Link>
          </div>

          <div className="bg-white border border-gray-200 rounded-2xl p-5 text-sm text-gray-500">
            <strong className="text-gray-900">Note:</strong> This is a hand-curated example for {example.name}.
            When you generate a skill file for your own brand, it&apos;s built fresh from your actual website — colors, copy, CTAs, fonts — not a template.
          </div>
        </div>
      </main>
    </div>
  )
}
