import Anthropic from '@anthropic-ai/sdk'
import type { BrandSignals } from './scraper'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

const FREE_SYSTEM_PROMPT = `You are a senior brand strategist and Claude Skills architect. Analyze the following brand data and generate a Claude Skill .md file. Any Claude instance loading this skill should produce content indistinguishable from the brand's actual voice.

IMPORTANT RULES:
- Output ONLY the skill file markdown. No explanations, no preamble.
- Start with the YAML frontmatter block.
- For FREE tier: include brand overview, 3 voice rules, visual identity (colors + fonts + logo), and 2 content templates (social media posts only).
- Make voice rules highly specific — extract actual patterns from the copy samples, not generic advice.
- Every DO/DON'T pair must use real examples that reflect the brand's actual language.
- End with: <!-- Generated by BrandSkill.com -->`

const PREMIUM_SYSTEM_PROMPT = `You are a senior brand strategist and Claude Skills architect. Analyze the following brand data and generate a complete Claude Skill .md file. Any Claude instance loading this skill should produce content indistinguishable from the brand's actual voice.

IMPORTANT RULES:
- Output ONLY the skill file markdown. No explanations, no preamble.
- Start with the YAML frontmatter block.
- For PREMIUM tier: include ALL sections — brand overview, 5 voice rules, full visual identity, all 6 content templates, anti-patterns, image generation guidance, and brand positioning.
- Make voice rules highly specific — extract actual patterns from the copy samples, not generic advice.
- Every DO/DON'T pair must use real examples that reflect the brand's actual language.
- Anti-patterns must be concrete and actionable — specific phrases, tones, or styles to avoid.
- Image generation guidance should be written as AI image generation prompts.
- End with: <!-- Generated by BrandSkill.com -->`

function buildUserMessage(signals: BrandSignals, tier: 'FREE' | 'PREMIUM', extras?: { about?: string; blog?: string; pricing?: string; competitor?: BrandSignals }): string {
  const colorList = signals.colors.map(c => `  - ${c.label}: ${c.hex} (used ${c.usage}x)`).join('\n')
  const fontList = Object.entries(signals.fonts).map(([k, v]) => `  - ${k}: ${v}`).join('\n')

  let msg = `
## Brand URL
${signals.url}

## Domain
${signals.domain}

## Meta
- Title: ${signals.meta.title}
- Description: ${signals.meta.description}

## Colors (top 5 by frequency)
${colorList || '  - None extracted'}

## Typography
${fontList || '  - None extracted'}

## Logo
${signals.logo || 'Not found'}

## Copy samples (first 3,000 chars from headings, paragraphs, buttons)
${signals.copy || 'None extracted'}

## CTAs (button/link text)
${signals.ctas.join(' | ') || 'None'}

## Navigation labels
${signals.navigation.join(' | ') || 'None'}
`

  if (tier === 'PREMIUM' && extras) {
    if (extras.about) msg += `\n## About page copy\n${extras.about}\n`
    if (extras.blog) msg += `\n## Blog sample\n${extras.blog}\n`
    if (extras.pricing) msg += `\n## Pricing page copy\n${extras.pricing}\n`
    if (extras.competitor) {
      msg += `\n## Competitor analysis (${extras.competitor.domain})\n`
      msg += `Copy: ${extras.competitor.copy.slice(0, 1000)}\n`
      msg += `CTAs: ${extras.competitor.ctas.join(' | ')}\n`
    }
  }

  msg += `\n## Tier\n${tier}\n`
  msg += `\n## Required output structure\n`

  if (tier === 'FREE') {
    msg += `
\`\`\`
---
name: [Brand Name] Brand Identity System
description: Apply [Brand Name]'s complete brand identity to all generated content.
---

## Brand overview
[2–3 sentences]

## Voice & tone rules
### Rule 1 — [Title]
DO: "[example]"
DON'T: "[example]"

### Rule 2 — [Title]
DO: "[example]"
DON'T: "[example]"

### Rule 3 — [Title]
DO: "[example]"
DON'T: "[example]"

## Visual identity
### Colors
- Primary: #hex — [usage rule]
[up to 5 colors]

### Typography
- Headlines: [font] — [rules]
- Body: [font] — [rules]

### Logo
- URL: [url]
- Usage: [rules]

## Content templates

### Social media posts
[IG formula with char count]
[LinkedIn formula with char count]
[X/Twitter formula with char count]

<!-- Generated by BrandSkill.com -->
\`\`\`
`
  } else {
    msg += `
\`\`\`
---
name: [Brand Name] Brand Identity System
description: Apply [Brand Name]'s complete brand identity to all generated content. Use whenever creating social posts, emails, ads, presentations, blog content, or naming products for [Brand Name].
---

## Brand overview
[2–3 sentences]

## Voice & tone rules
### Rule 1–5 (all five, with DO/DON'T examples)

## Visual identity
### Colors (all 5), Typography, Logo

## Content templates
### Social media posts (IG, LinkedIn, X, TikTok — with char counts)
### Email (subject formulas, preview text, CTA style)
### Ad creatives (headline formula, body copy, CTA patterns)
### Pitch decks (slide format, color/font application)
### Blog covers (title formulas, intro paragraph pattern)
### Product naming (naming conventions, phonetics, examples)

## Anti-patterns
[5 concrete things this brand must NEVER do]

## Image generation guidance
[Mood, style, composition, palette — written as AI image generation instructions]

## Brand positioning
[Target audience, value proposition, differentiation — 3–4 sentences]

<!-- Generated by BrandSkill.com -->
\`\`\`
`
  }

  return msg
}

export async function generateSkillFile(
  signals: BrandSignals,
  tier: 'FREE' | 'PREMIUM',
  extras?: { about?: string; blog?: string; pricing?: string; competitor?: BrandSignals }
): Promise<string> {
  const systemPrompt = tier === 'PREMIUM' ? PREMIUM_SYSTEM_PROMPT : FREE_SYSTEM_PROMPT
  const userMessage = buildUserMessage(signals, tier, extras)

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: tier === 'PREMIUM' ? 4096 : 2048,
    system: systemPrompt,
    messages: [{ role: 'user', content: userMessage }],
  })

  const text = response.content[0]
  if (text.type !== 'text') throw new Error('Unexpected response type from Claude')
  return text.text
}
